// States
export const STATE_NONE = 'STATE_NONE';
export const STATE_READY = 'STATE_READY';
export const STATE_PLAYING = 'STATE_PLAYING';
export const STATE_PAUSED = 'STATE_PAUSED';
export const STATE_STOPPED = 'STATE_STOPPED';
export const STATE_BUFFERING = 'STATE_BUFFERING';
export const STATE_CONNECTING = 'STATE_CONNECTING';

// Capabilities
export const CAPABILITY_PLAY = 'CAPABILITY_PLAY';
export const CAPABILITY_PLAY_FROM_ID = 'CAPABILITY_PLAY_FROM_ID';
export const CAPABILITY_PLAY_FROM_SEARCH = 'CAPABILITY_PLAY_FROM_SEARCH';
export const CAPABILITY_PAUSE = 'CAPABILITY_PAUSE';
export const CAPABILITY_STOP = 'CAPABILITY_STOP';
export const CAPABILITY_SEEK_TO = 'CAPABILITY_SEEK_TO';
export const CAPABILITY_SKIP = 'CAPABILITY_SKIP';
export const CAPABILITY_SKIP_TO_NEXT = 'CAPABILITY_SKIP_TO_NEXT';
export const CAPABILITY_SKIP_TO_PREVIOUS = 'CAPABILITY_SKIP_TO_PREVIOUS';
export const CAPABILITY_JUMP_FORWARD = 'CAPABILITY_JUMP_FORWARD';
export const CAPABILITY_JUMP_BACKWARD = 'CAPABILITY_JUMP_BACKWARD';
export const CAPABILITY_SET_RATING = 'CAPABILITY_SET_RATING';
export const CAPABILITY_LIKE = 'CAPABILITY_LIKE';
export const CAPABILITY_DISLIKE = 'CAPABILITY_DISLIKE';
export const CAPABILITY_BOOKMARK = 'CAPABILITY_BOOKMARK';

// Pitch algorithms
export const PITCH_ALGORITHM_LINEAR = 'PITCH_ALGORITHM_LINEAR';
export const PITCH_ALGORITHM_MUSIC = 'PITCH_ALGORITHM_MUSIC';
export const PITCH_ALGORITHM_VOICE = 'PITCH_ALGORITHM_VOICE';

// Rating Types
export const RATING_HEART = 'RATING_HEART';
export const RATING_THUMBS_UP_DOWN = 'RATING_THUMBS_UP_DOWN';
export const RATING_3_STARS = 'RATING_3_STARS';
export const RATING_4_STARS = 'RATING_4_STARS';
export const RATING_5_STARS = 'RATING_5_STARS';
export const RATING_PERCENTAGE = 'RATING_PERCENTAGE';
